artifact_uri: file:///D:/work/neural-networks-fundamentals/.laborantum/mlflow_logs/110977014004178558/29c8f8ab1a0c44e1a19cdb597591a283/artifacts
end_time: 1784277085540
entry_point_name: ''
experiment_id: '110977014004178558'
lifecycle_stage: active
run_id: 29c8f8ab1a0c44e1a19cdb597591a283
run_name: two_layer_fcnn_test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1784277057810
status: 3
tags: []
user_id: user
