artifact_uri: file:///D:/work/neural-networks-fundamentals/.laborantum/mlflow_logs/110977014004178558/7fbfe3e7aec441e9ba64ec424947f9e2/artifacts
end_time: 1784400977134
entry_point_name: ''
experiment_id: '110977014004178558'
lifecycle_stage: active
run_id: 7fbfe3e7aec441e9ba64ec424947f9e2
run_name: word2vec_hsoftmax_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1784400971930
status: 3
tags: []
user_id: user
