artifact_uri: file:///D:/work/neural-networks-fundamentals/.laborantum/mlflow_logs/110977014004178558/2b30e9fd6347492fbbe53da73c3132bd/artifacts
end_time: 1784277017011
entry_point_name: ''
experiment_id: '110977014004178558'
lifecycle_stage: active
run_id: 2b30e9fd6347492fbbe53da73c3132bd
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1784276948739
status: 3
tags: []
user_id: user
